import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const pluginDir = path.join(__dirname, 'joviz-demo-vault', '.obsidian', 'plugins', 'journal-visualizer');

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Copy to demo vault plugin folder
	try {
		if (!fs.existsSync(pluginDir)) {
			fs.mkdirSync(pluginDir, { recursive: true });
		}
		fs.copyFileSync('main.js', path.join(pluginDir, 'main.js'));
		fs.copyFileSync('manifest.json', path.join(pluginDir, 'manifest.json'));
		fs.copyFileSync('styles.css', path.join(pluginDir, 'styles.css'));
		if (fs.existsSync('data.json')) {
			fs.copyFileSync('data.json', path.join(pluginDir, 'data.json'));
		}
		console.log(`✓ Plugin built and copied to demo vault`);
	} catch (err) {
		console.warn(`Note: Could not copy to demo vault (${err.message}). Run 'npm run generate-demo-vault' first.`);
	}
	process.exit(0);
} else {
	await context.watch();
	// Watch mode: copy files on rebuild
	context.onEnd(async () => {
		try {
			if (fs.existsSync(pluginDir)) {
				fs.copyFileSync('main.js', path.join(pluginDir, 'main.js'));
				fs.copyFileSync('styles.css', path.join(pluginDir, 'styles.css'));
				console.log(`✓ Plugin copied to demo vault`);
			}
		} catch (err) {
			// Silently fail in watch mode
		}
	});
}
